apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: kubernetes-google-deployment
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Kubernetes Deployment
    # source:
    #   repo: https://github.com/GoogleCloudPlatform/google-kubernetes-deployment-module.git
    #   sourceType: git
    #   dir: /modules/v2
    actuationTool:
      flavor: Kubernetes
      # version: TBD
    description: {}
  interfaces:
    variables:
      - name: deployment_name
        description: Name of the deployment
        varType: string
        required: true
      - name: namespace
        description: Namespace of the deployment
        varType: string
        required: true
      - name: replica_count
        description: Replica count of the deployment
        varType: number
        defaultValue: 1
      - name: service_account
        description: Kuberenetes Service account name used to commnicate with Kubernetes API server
        varType: string
        required: true
      - name: labels
        description: Kuberentes labels
        varType: map(string)
        defaultValue: {}
      - name: annotations
        description: Kuberentes annotations
        varType: map(string)
        defaultValue: {}
      - name: service_account_name
        description: Kubernetes Service Account required to communitcate with Kubernetes API server
        varType: string
        defaultValue: default
        required: true
      - name: containers
        description: Container to run on the deployments.
        varType: |-
          list(object({
              name = string
              image = string
              ports = optional(list(object({
                containerPort = number
                name          = string
              })))
              env = optional(list(object({ 
                name  = string
                value = string
              })))
              resources = optional(object({
                limits = optional(object({
                  cpu    = optional(string)
                  memory = optional(string)
                }))
                requests = optional(object({
                  cpu    = optional(string)
                  memory = optional(string)
                }))
              }))
            }))
        required: true
        connections:
          - source:
              source: Service
            spec:
              outputExpr: "{value: name + \".\" + namespace + \":\" + ports.port, name: name + \"_SERVICE_ADDR\"}"
              inputPath: env